### ISSUE TITLE
requests.exceptions.ConnectionError

### ISSUE THREAD

**Issue by tschmoderer** [deethon/deethon#20]
I got an error when I try to download multiple albums in a row. 

I believe it is due to a connection closed by deezer. Maybe you should include a timer to reset the connection after a certain time.

I attached the error log bellow: 
[error.log](https://github.com/deethon/deethon/files/4750740/error.log)

**Comment by aykuxt** [comment]
Indeed, I was able to reproduce. I will investigate as soon as possible. Thank you for the report.

**Comment by aykuxt** [comment]
This error has not occurred for a long time now and I think it's not related to the library. If you don't face this problem again I will close the issue.
